### PR TITLE
Fix mixed CDATA usage

### LINKED ISSUE #260: CDATA usage in array of tags gives empty string instead of value
I am trying to get this failing test to work, but not getting anywhere.

```swift
import XCTest
import XMLCoder

final class CDATAEntryTest: XCTestCase {
    private struct DataEntry: Codable, Equatable {
        let value: String
        enum CodingKeys: String, CodingKey {
            case value = ""
        }
    }
    
    private struct Container: Codable, Equatable {
        let data: [DataEntry]
    }
    
    private let xml =
        """
        <container>
           <data><![CDATA[lorem ipsum]]></data>
           <data>bla bla</data>
        </container>
        """.data(using: .utf8)!
    
    func testXMLWithCDataDataEntries() throws {
        let decoder = XMLDecoder()
        let result = try decoder.decode(Container.self, from: xml)
        XCTAssertEqual(result, Container(data: [.init(value: "lorem ipsum"), .init(value: "bla bla")])) // FAILS: got: ["", "bla bla"], but expected: ["lorem ipsum", "bla bla"]
    }
}
```

### PR DESCRIPTION
**Pull request by johankool**
Fixes #260

### CODE REVIEW

**Comment by Joannis** [comment]
Thanks for your contribution! I'll let the tests run, and run it through myself. But it looks good for sure.

**Comment by Joannis** [comment]
Done

**Comment by johankool** [comment]
Not sure what to do about this. I don't have Xcode 13.1 on macOS 11.0 available to me, so can't easily reproduce. Not sure why anyone would still use that either.

**Comment by Joannis** [comment]
I agree with you @johankool , it's an old platform. And even the Xcode build is old for the specific platform. If you want, you can replace the target with a Ventura / Xcode 14 one to get the tests running. I'll make sure we'll also add Linux/5.7 and Linux/5.8 after that.

**Comment by Joannis** [comment]
Actually, the latest tests (Xcode 14, macOS 12) never ran to begin with. So I do think there's _something_ at play.

**Review by Joannis — APPROVED** [review]

**Comment by Joannis** [comment]
I feel like this is a github runner issue, so I've merged it.

**Pull request merged**
